version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: orbit
      POSTGRES_PASSWORD: inorbit
      POSTGRES_DB: orbit
    ports:
      - "5432:5432"