services:
  postgres:
    container_name: postgres
    image: bitnami/postgresql:17.2.0
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_NAME=postgres
    ports:
      - "5432:5432"
