#:schema node_modules/wrangler/config-schema.json
name = "manage-wise-api"
main = "src/index.ts"
account_id = "4aa839773109421527f1f0147e3557c0"
compatibility_date = "2024-11-12"

compatibility_flags = ["nodejs_compat"]

# Development
# vars = { NEON_DATABASE_URL = "postgresql://postgres:postgres@localhost:5432/manage-wise" }

minify = true
